---
title: "**News**"
comments: false
about:
  template: jolla
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/qvv5013

    - icon: github
      text: Github
      href: https://github.com/vuqv

title-block-banner: true
---



<table class="table table-hover responsive-lg">
  <thead>
    <tr class="card-header">
      <th scope="col">Dates</th>
      <th scope="col">Events</th>
    </tr>
  </thead>
  <tbody>
    <tr >
      <td scope="row" class="text-center align-middle">
        08/08/2025
      </td>
      <td class="text-center align-middle">
        Our new article “Non-­native entanglement protein misfolding observed in all-­atom simulations and supported by experimental structural ensembles” has been out in Science Advances. [Read more](https://www.science.org/doi/10.1126/sciadv.adt8974)
      </td>
    </tr>
  <tr >
      <td scope="row" class="text-center align-middle">
        25/04/2024
      </td>
      <td class="text-center align-middle">
        Quyen Vu's PhD thesis has been selected for the Best PhD thesis in 2023 of Institute of Physics, Polish Academy of Sciences
      </td>
    </tr>
  <tr >
  <tr >
      <td scope="row" class="text-center align-middle">
        01/04/2024
      </td>
      <td class="text-center align-middle">
        Quyen Vu has started his job as a postdoc in O'Brien Lab at Department of Chemistry, Pennsylvania State University.
      </td>
    </tr>
  <tr >
  <tr >
      <td scope="row" class="text-center align-middle">
        18/12/2023
      </td>
      <td class="text-center align-middle">
        Quyen Vu has successfully defended his Ph.D. in Physics at the Institute of Physics, Polish Academy of Sciences. Congratulations on this significant accomplishment, Quyen!
      </td>
    </tr>
  <tr >
      <td scope="row" class="text-center align-middle">
        06/11/2023
      </td>
      <td class="text-center align-middle">
        Quyen Vu's PhD thesis has received three unanimous, positive reviews, all concurring that it merits distinction.
        He will have a public defense on 18 December 2023 at 2 PM (CEST time).
        [Details](https://www.ifpan.edu.pl/en/activities/doctoral-dissertations/2023/quyen-van-vu.html){target="_blank"}
      </td>
    </tr>

    <tr >
      <td scope="row" class="text-center align-middle">
        01/09/2023
      </td>
      <td class="text-center align-middle">
        Quyen Vu has successfully passed the Physics Exam at IFPAN with a score of 4.5/5. 
        This marks the final examination before he defends his PhD thesis. 
        The exam covered General Physics and profile-specific themes.
      </td>
    </tr>
    
    <tr >
      <td scope="row" class="text-center align-middle">
        06/07/2023 
      </td>
      <td class="text-center align-middle">
        Quyen Vu delivered a brief presentation about his PhD thesis in front of the Scientific Council of IFPAN.
      </td>
    </tr>

    <tr >
      <td scope="row" class="text-center align-middle">
        22/06/2023
      </td>

      <td class="text-center align-middle">
        Quyen Vu has submitted his PhD thesis. 
      </td>
    </tr>

    <tr >
      <td scope="row" class="text-center align-middle">
        17/10/2018
      </td>
      <td class="text-center align-middle">
        Quyen Vu started his PhD journey at the Institute of Physics, Polish Academy of Sciences.
        He will work with Prof. Mai Suan Li and Prof. Ed O'Brien from Penn State University, focusing on "Protein Folding on Ribosome".
      </td>
    </tr>

  </tbody>
</table>

