---
title: "**Publications**"
comments: false
about:
  template: solana
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/qvv5013
    - icon: github
      text: Github
      href: https://github.com/vuqv

title-block-banner: true
---

<div style="text-align: left">

<!--
Open link in new tab: add {target="_blank"}
-->

1) <u>Vu, Q. V.</u>, Sitarik, I., Jiang, Y., Xia, Y., Sharma, P., Yadav, D., Song, H., Li, M. S., Fried, S. D., & O’Brien, E. P. (2025).
`Non-native entanglement protein misfolding observed in all-atom simulations and supported by experimental structural ensembles.`
Science Advances, 11(32).
[Read more](https://doi.org/10.1126/sciadv.adt8974)

1) <u>Vu, Q. V.</u>, Sitarik, I., Li, M. S., & O’Brien, E. P.
`Noncovalent Lasso Entanglements are Common in Experimentally Derived Intrinsically Disordered Protein Ensembles and Strongly Influenced by Protein Length and Charge.`
The Journal of Physical Chemistry B (2025).
[Read more](https://doi.org/10.1021/acs.jpcb.5c01260){target="_blank"}-ACS Editors' Choice

1) Lan, P. D., Nissley, D. A., Sitarik, I., <u>Vu, Q. V.</u>, Jiang, Y., To, P., Xia, Y., Fried, S. D., Li, M. S., & OBrien, E. P.
`Synonymous Mutations Can Alter Protein Dimerization Through Localized Interface Misfolding Involving Self-entanglements.`
Journal of Molecular Biology 2024, 436(6), 168487
[Read more](https://doi.org/10.1016/j.jmb.2024.168487){target="_blank"}


1) Halder, R.; Nissley, D. A.; Sitarik, I.; Jiang, Y.; Rao, Y.; <u>Vu, Q. V</u>; Li, M. S.; Pritchard, J.; O’Brien, E. P.
`How Soluble Misfolded Proteins Bypass Chaperones at the Molecular Level.`
Nat. Commun. 2023, 14 (1), 3689.
[Read more](https://doi.org/10.1038/s41467-023-38962-z){target="_blank"}


1) <u>Vu, Q. V</u>; Nissley, D. A.; Jiang, Y.; O’Brien, E. P.; Li, M. S.
`Is Posttranslational Folding More Efficient Than Refolding from a Denatured State: A Computational Study.`
J. Phys. Chem. B 2023, 127 (21), 4761–4774.
[Read more](https://pubs.acs.org/doi/10.1021/acs.jpcb.3c01694){target="_blank"}

1) <u>Vu, Q. V</u>; Sitarik, I.; Jiang, Y.; Yadav, D.; Sharma, P.; Fried, S. D.; Li, M. S.; O’Brien, E. P.
`A Newly Identified Class of Protein Misfolding in All-atom Folding Simulations Consistent with Limited Proteolysis Mass Spectrometry.`
(In Review). [PrePrint available](https://www.biorxiv.org/content/10.1101/2022.07.19.500586v2){target="_blank"}

1) Leininger, S. E.; Rodriguez, J.; <u>Vu, Q. V.</u>; Jiang, Y.; Li, M. S.; Deutsch, C.; O’Brien, E. P.
`Ribosome Elongation Kinetics of Consecutively Charged Residues Are Coupled to Electrostatic Force.`
Biochemistry 2021, 60, 43, 3223–3235. [Read more](https://pubs.acs.org/doi/10.1021/acs.biochem.1c00507){target="_blank"}

1) <u>Vu, Q. V.</u>; Jiang, Y.; Li, M. S.; O’Brien, E. P.
`The Driving Force for Co-translational Protein Folding is Weaker In the Ribosome Vestibule due to Greater Water Ordering.`
Chemical Science 2021. 12, 11851-11857. [Read more](https://pubs.rsc.org/en/content/articlelanding/2021/sc/d1sc01008e){target="_blank"}

1) Nissley, D. A.; <u>Vu, Q. V.</u>; Trovato, F.; Ahmed, N.; Jiang, Y.; Li, M. S.; O’Brien, E. P.
`Electrostatic Interactions Govern Extreme Nascent Protein Ejection Times from Ribosomes and Can Delay Ribosome Recycling.`
J. Am. Chem. Soc. 142, 13, 6103-6110 (2020). [Read more](https://pubs.acs.org/doi/10.1021/jacs.9b12264){target="_blank"}



</div>
